version: '3'
services:
  api:
      container_name: API
      build:
        context: .dockerfiles
        dockerfile: DockerfileAPI
      ports:
        - 8888:8888
      volumes:
        - ./api:/app
      command: php -S 0.0.0.0:8888 public/index.php
      restart: always
      networks:
        - rede
  banco:
    image: mysql:5.7
    container_name: base
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3306:3306
    networks:
      - rede
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  rede:
    driver: bridge