version: '3'
services:
  api:
      container_name: API
      build:
        context: .dockerfiles
        dockerfile: DockerfileAPI
      ports:
        - 8888:8888
      volumes:
        - ./api:/app
      command: php -S 0.0.0.0:8888 public/index.php
      restart: always
      networks:
        - rede
networks:
  rede:
    driver: bridge