version: '3'
services:
  api:
      container_name: API
      build:
        context: .dockerfiles
        dockerfile: DockerfileAPI
      ports:
        - 8888:8888
      volumes:
        - ./api:/app
      restart: always
      networks:
        - rede
networks:
  rede:
    driver: bridge